### ISSUE TITLE
DOCS - proposer une arborescence exemple

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoNature-mobile#14]
Pour la 1.2.0, dans le répertoire install de la doc, proposer une arborescence depuis la racine de la carte sd externe mais aussi de la mémoire interne. Cette arborescence doit comporter les fichiers nécessaires au fonctionnement des applications mobiles.
Pour les fichiers carto, très lourds, placer un fichier ``readme.md`` dans le répertoire où sont attendus les 3 mbtiles (unities, scan et ortho.mbitles). Ce fichier présente les fichiers attendus et leur fonction. Il renvoie à la doc décrivant le mode de création de ces fonds.

**Comment by camillemonchicourt** [comment]
Oui bonne idee.
Les structures n'auront plus qu'à dupliquer et adapter cette arborescence.
