### ISSUE TITLE
OccTax mobile - Champs saisissables

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-mobile#19]
GeoNature est en cours de refonte totale. 
Les modules Contact Faune et Flore n'existent plus mais ont été regroupés dans un module unique nommé OccTax. 
Il sert à faire du Contact Faune-Flore-Fonge dans un module unique, qui s'appuie sur le standard Occurrences de taxons du SINP.

La saisie sur mobile devant être plus simple et allégée, voici la gestion proposée pour les différents en saisie Occtax mobile : 

**RELEVE :** 

- Geom : Point uniquement. Le zoom de saisie minimum sera paramétré dans le fichier de conf présent sur le terminal mobile
- Observateurs : Liste. Observateur renseigné par défaut selon conf terminal. Possibilité d'en ajouter à partir de la liste. Observateurs_as_text non géré dans un premier temps
- Jeu de données : Liste modifiable basée sur une liste dans le fichier de conf du terminal mobile. Plus paramètre permettant de définir le JDD sélectionné par défaut dans la liste déroulante
- Technique d'observation : Valeur par défaut de la BDD, pas en interface, ni conf mobile. En passant, le virer de la BDD et de Occtax web le temsp de clarifier ?
- Date min : Aujourd'hui par défaut. Pas de date max, ni d'heure
- Altitude : Pas en interface. Trigger dans la BDD ? Attention en Web c'est calculé au niveau du front
- Commentaire relevé : OK mais à la fin de la saisie avec les commentaires Taxons
- Précision : Valeur par défaut de la BDD

**TAXONS :**

- Taxon : OK. Une seule liste FR/LATIN. Filtre par règne/groupe. Plus champs de recherche pour filtrer la liste. Le bouton FR/LATIN permet de 
- Méthode d'observation : Valeur par défaut de la BDD, modifiable en interface. Liste conditionnée par le taxon
- Etat biologique : Idem méthode d'observation
- Champs AVANCE : On peut les modifier à la fin. Valeurs par défaut de la BDD préremplies

**DÉNOMBREMENT :** 

On propose de garder tout, mais à la fin de la saisie, optionnel. Sinon ça pousse les valeurs par défaut comme en WEB (1 individu inconnu)

**Comment by camillemonchicourt** [comment]
Un appel d'offre a été lancé : http://www.vanoise-parcnational.fr/fr/marches-publics/marche-procedure-adaptee-ndeg-41-2018

**Comment by camillemonchicourt** [comment]
Le document est ici : http://geonature.fr/documents/cctp/

**Comment by camillemonchicourt** [comment]
Un nouvel appel d'offre a été lancé : http://www.vanoise-parcnational.fr/fr/marches-publics/marche-procedure-adaptee-ndeg-105-2018
Dossier complet : https://www.marches-publics.gouv.fr/app.php/consultation/402072

**Comment by gildeluermoz** [comment]
tu me rafraichirais la mémoire stp : coté mobile, c'est quoi le projet pour flore prioritaire et flore territoire ? 



		
	Gil DELUERMOZ 
Chargé de mission développement web et bases de données 

Parc national des Écrins 
Tél : +33 (0) 4 92 40 20 38 (lundi et mardi) 
+33 (0)4 92 21 08 49 (mercredi et jeudi matin) 
[ http://www.ecrins-parcnational.fr/ | www.ecrins-parcnational.fr ] 

[ http://actu.ecrins.info/ ] 


De: "Camille Monchicourt" <notifications@github.com> 
À: "PnEcrins/GeoNature-mobile" <GeoNature-mobile@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Lundi 5 Novembre 2018 10:40:02 
Objet: Re: [PnEcrins/GeoNature-mobile] OccTax mobile - Champs saisissables (#19) 



Un nouvel appel d'offre a été lancé : [ http://www.vanoise-parcnational.fr/fr/marches-publics/marche-procedure-adaptee-ndeg-105-2018 | http://www.vanoise-parcnational.fr/fr/marches-publics/marche-procedure-adaptee-ndeg-105-2018 ] 
Dossier complet : [ https://www.marches-publics.gouv.fr/app.php/consultation/402072 | https://www.marches-publics.gouv.fr/app.php/consultation/402072 ]

**Comment by camillemonchicourt** [comment]
Le CCTP est consultable ici : https://geonature.fr/documents/cctp/2018-08-CCTP-GeoNature-mobile-v2.pdf
La suite des discussions dans le dépôt dédié : https://github.com/PnX-SI/gn_mobile_occtax/issues/1
