### ISSUE TITLE
Nettoyer la DOC

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-mobile#4]
J'ai commencé à nettoyer et lister ici : https://github.com/PnEcrins/GeoNature-mobile/tree/master/docs

Mais il faudrait la regrouper et retirer tout ce qui est caduque.

A suivre....

**Comment by camillemonchicourt** [comment]
Dans la doc sur la génération des mbtiles avec MOBAC, @gildeluermoz propose quelques compléments : 

Il serait utile la compléter avec des infos sur la manière de créer un nouveau mapsource pour les unités geo notamment (ci-dessous)

________________________________

Si la couche des unités geo a été ajoutée dans le schéma layers de la base geonaturedb, il est très simple et rapide de créer le unities.mbtiles nécessaire au fonctionnement des applis contact faune et contact invertébrés.

* Pour cela, créer un nouveau fichier mapsource nommé unitesgeo.xml. Y mettre ceci en adaptant l'url du wms de geonature :

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<customWmsMapSource>
   <name>Unites geo GeoNature</name>
   <minZoom>0</minZoom>
   <maxZoom>18</maxZoom>
   <tileType>PNG</tileType>
   <version>1.1.1</version>
   <layers>unitesgeo</layers>
   <url>http://localhost/wmsgeonature?</url>
   <coordinatesystem>EPSG:4326</coordinatesystem>
   <aditionalparameters><![CDATA[&TRANSPARENT=true]]></aditionalparameters>
</customWmsMapSource>
```

note :: si une installation local de geonature est disponible, le tuilage sera plus rapide (selon les performances de la machine !)

* Placer ce fichier dans le répertoire ``mapsources`` de MOBAC
* Ouvrir l'application mobac
* Menu Atlas --> nouvel atlas (Mbtiles SQLite) et le nommer ``unities``
* Sélectionner la source de carte ``Unites geo GeoNature``
* Cocher tous les niveaux de zoom entre 0 et 18 (0 et 16 si pas d'ortho). Attention, les niveaux 17 et 18 peuvent générer de nombreuses tuiles si le territoire est grand
* Menu Sélection --> mode de sélection --> Polygonal puis dessiner le contour de la couche au plus près pour éviter de créer trop de tuiles transparentes vides.
* Ajouter la sélection (nom = unities)
* Créer l'atlas (bouton). Le fichier se trouve dans le répertoire ``atlases`` de MOBAC

**Comment by gildeluermoz** [comment]
Complément:
Il est possible de supprimer toutes les tuiles vides qui font généralement 334 octets (à vérifier sur votre fichier): 
* ouvrir le fichier ``unities.mbtiles`` avec un éditeur sqlite3 (sqliteman par exemple) ou en console.
* Rechercher les tuiles vides : ``SELECT count(*) FROM tiles WHERE length(tile_data) = 334;``
* Supprimer les tuiles vides : ``DELETE FROM tiles WHERE length(tile_data) = 334;``
* Supprimer l'espace libérer : ``vacuum;``
La taille de votre fichier peut ainsi être fortement réduite.
