### ISSUE TITLE
FLORE PRIORITAIRE - le nombre de relevé non synchronisé n'est pas mis à jour

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoNature-mobile#6]
Lorsque l'on fini une saisie et que l'on choisi de commencer une nouvelle saisie, on arrive sur la page d'accueil et le nombre de relevés non synchronisés n'est pas mis à jour. Il faut quitter l'appli et y revenir pour rafraîchir cette information.

**Comment by sgrimault** [comment]
Sans doute lié à #5

**Comment by gildeluermoz** [comment]
Ok, le soucis est corrigé.
