### ISSUE TITLE
FLORE PRIORITAIRE - le positionnement et le zoom de la carte n'est pas mémorisé entre 2 AP

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoNature-mobile#9]
J5 et GNote1, si je saisi une 2ème aire de présence, la carte se place sur l'emprise générale (il serait préférable de se positionner sur l'emprise de l'ap déjà saisie.
Sur certains terminaux, ceci ne se produit pas.

**Comment by sgrimault** [comment]
Je le reproduis facilement si on reprend une saisie en cours sur laquelle on souhaite ajouter une autre AP mais pas si on ajoute au moins deux APs (la seconde gardera l'état de la carte tel qu'elle a été laissée précédemment).
Je te proposerai bien de faire comme dans l'étape ZP où on affiche en lecture seule les APs sauf qu'ici on n'affiche que les précédentes APs sur laquelle j'applique un zoom automatique centré sur ces APs ?
L'avantage est qu'on pourra voir aisément sur la carte les APs déjà saisies surtout si on reprend une saisie qui a été suspendue.

**Comment by gildeluermoz** [comment]
Oui parfait. On fait comme ça

**Comment by gildeluermoz** [comment]
Nickel, c'est parfait comme ça. Ca fonctionne bien et c'est clair pour l'utilisateur. Le fait d'avoir le dessin des AP précédentes est une aide à la saisie intéressante.
